language: node_js
node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"
git:
  depth: 1
before_install:
  - export CC=clang
  - export CXX=clang++
  - export npm_config_clang=1
  - npm install nodegit --build-from-source